BBBBBBB BBBBBBBBBBB

BBBBB BBB
    BBBB BBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBB
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                BBB BBBBBBBBB BB BBBBB
                    BBBBBBB BBBBBBBBBBBBBBBB
                BBBBBB
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

BBBBBBBB