BBBBBBB BBBBBBBBBBB

BBBBB BBB
    BBBB BBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBB
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                BBB BBBBBB BB BBBBBBB
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
                BBBBBB
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB