BBBBB BBBBBB
    BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
            XXX XXXXXXXXXX XXXXXXXXXXXX
                BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXXX XXXXXXXX
                        XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                    XXXXX
                BBBB
                    XXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBXXXXXXXXXXXXXX
                    XXXXX
                BBBBB
                BB BBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXXX XXXXXXXX
                        XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                    XXXXX
                BBBB
                    XXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBXXXXXXXXXX
                    XXXXX
                BBBBB
                BB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXXX XXXXXXXX
                        XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                    XXXXX
                BBBB
                    XXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXXXXXXXXXXXXX
                    XXXXX
                BBBBB
                XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXX
                    XXXXXX
                XXXXX
            XXXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
        XXXXXX
    BBBB
        XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
        XXXXXX
    BBBBB
BBBBBBBB