# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='note',
            name='comments',
            field=models.ManyToManyField(to='post.Comment'),
        ),
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(to='post.Like'),
        ),
    ]
