# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20161018_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='comments',
            field=models.ManyToManyField(blank=True, to='post.Comment'),
        ),
        migrations.AlterField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(blank=True, to='post.Like'),
        ),
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
