# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20161101_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='comments',
            field=models.ManyToManyField(to='post.Comment'),
        ),
        migrations.AlterField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(to='post.Like'),
        ),
    ]
