

XXXX XXXXXXXXXXXXXXXXXXX
    BBBB BBBBBB
BBBB BBBBBBBBBBBBB
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXX
    XXXX XXXXXXXXXXXXXXXXXXX
        BB BBBB BB BBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBXX
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXX
                        FFFFFFFFFFFFFFFFFFFFFFFF
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        FFFFFFFFFFFFFFFFFFFFFFFF
                    XXXXXX
                    XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXX
                XXXXXXX
            XXXXXX
        BBBB
            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBXX
                BBBBBBBBBB
                
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX
            XXXXXXX
        BBBBB
    XXXXXX
XXXXXX