

XXXXXXXX XXXXXXXXXXXXXXX
    BBBB BBBBBB
    BBBB BBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
                        XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                          XXXX
                    XXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                FFFFFFFFFFF FFFF
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                    FFFFFFFFFF
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX

                    XXXX XXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBB BBBBBBBBBBBBBBBXX
                            XXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXX

                                BBBBBBBBBB
                                XXXX XXXXXXXXXXXXXXXXXXX
                                     FFFFFFFFFFFFFFFFFFFFFFFFFFFF
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
                                    XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXX


                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXXX
                    XXXXXX

                XXXXXX
            XXXXXX

            XXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXX
                        XXXX
                    XXXXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXX
                XXXX
            XXXXXX

            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBXX
                    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX                        XXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
                        XXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXX
XXXXXXXXXX