# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_myfriend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfriend',
            name='friend',
        ),
        migrations.AddField(
            model_name='achievment',
            name='avatar',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='achievment',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MyFriend',
        ),
    ]
