

XXXXXXXX XXXXXXXXXXXXXXXXX
    BBBB BBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXFFFFFFFFFFF FFFFFFFFFFFXXXX
        XXXXXX
    XXXX
XXXXXXXXXX