

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    BBBB BBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
              XXXX
        XXXX
    XXXXXX
XXXXXXXXXX