XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX X XX
        XXXXXXXXXXXXXXXXXXXXXX X XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX X XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXX XX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX X XX
            X
            XXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX X XX
            X
        XXX
    XXX
XXXXXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    BBBB BBBBBB
    BBBB BBBBBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBXX
    BBBBB BBBB
        BB BBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXX
            XXXXXX
            BB BBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX

                            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXXXXXXX
                                    BBBBBBBBBB
                                    XXXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXX
                                        FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX
                                    XXXX XXXXXXXXXXXXXXXXX
                                        XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                    XXXXXX
                                XXXXXXXX
                            XXXXXXX

                        XXXXXX
                        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                             XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                            XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                BBBBBBBBBB
                                FFFFFFFFFFFFFFFFFFFFFFFF
                                FFFFFFFFFFFFFFFFFFFFFFFF
                                XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
                            XXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            BBBBB
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    BB BBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX

                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX
                                XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX
                            XXXXXXXXX

                        XXXXXX
                    BBBB
                        XXXX XXXXXXXXXXXXXXXXXX
                            XXXX XXXXX
                        XXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
        BBBBB
    BBBBBBBB
XXXXXX