XXXXXXXXXXXXXX
XXXX
BBB BBBBBBBBB BB BBBBB
    XXXX
         XXXX
         X  XXXX
        XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
    XXXXX
BBBBB
    XXXXXX XXXXXXXX XXXXXXXXX
BBBBBB
XXXXX